### ISSUE TITLE
Travis-CI

### ISSUE THREAD

**Issue by icoz** [dgovil/PySignal#4]
Would you like to add Travis-CI support for your tests? (https://travis-ci.org/)
config like this: https://github.com/icoz/habraparse/blob/master/.travis.yml
some doc: https://docs.travis-ci.com/
And add badge to Readme like this:
[![Build Status](https://travis-ci.org/icoz/habraparse.svg?branch=master)](https://travis-ci.org/icoz/habraparse)
`[![Build Status](https://travis-ci.org/icoz/habraparse.svg?branch=master)](https://travis-ci.org/icoz/habraparse)`

**Comment by dgovil** [comment]
Good point. Added Travis support for 2.7 and 3.5
